import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section>
        <h1>We help people to take control of their health.</h1>
        <h5>
          Find out how to sleep better, gain more energy & reach your ideal body
          goals.
        </h5>
        <img src="https://images.pexels.com/photos/7780771/pexels-photo-7780771.jpeg?auto=compress&cs=tinysrgb&w=800" />
        <h1>Our Mission</h1>
        <p>
          Our mission is to help men and women achieve their goals through
          highly researched tips and recommendations.{" "}
        </p>
        <p>
          We believe everyone should do their best to prioritize their health
          now, so that they can enjoy more of their best lives possible in the
          future.
        </p>
        <p>
          And we’re here to help. This website contains articles, quizzes, and
          recommended resources so anyone can make a big difference in their
          health goals
        </p>
        <p>
          “Good health is not something we can buy. However, it can be an
          extremely valuable savings account.” - Anne Wilson Schaef
        </p>
        <p>
          “Take care of the body. It’s the only place you have to live.” - Jim
          Rohn
        </p>
      </section>
      <Footer />
    </>
  );
}
